# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Install GitLab-Runner dependencies
  ansible.builtin.apt:
    pkg:
      - debian-archive-keyring
      - apt-transport-https
      - gnupg
    state: present
    update_cache: yes

- name: Install gitlab-runner via apt-get
  when: gitlab_runner_deb_file | length == 0

  block:
    - name: "Add packages repository packages.gitlab.com/runner/gitlab-runner"
      ansible.builtin.deb822_repository:
        name: "gitlab-runner"
        types: "deb"
        uris: "https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}/"
        suites: "{{ ansible_distribution_release }}"
        components: "main"
        signed_by: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
        state: "present"
        enabled: true

    - name: "Use APT pinning for Debian os"
      ansible.builtin.template:
        src: "pin-gitlab-runner.pref.j2"
        dest: "/etc/apt/preferences.d/pin-gitlab-runner.pref"
        owner: "root"
        group: "root"
        mode: '0644'
      when: "ansible_distribution == 'Debian'"

    - name: Install gitlab-runner with downgrade option
      ansible.builtin.apt:
        name: "{{ gitlab_runner_package_name }}"
        state: present
        update_cache: yes
        allow_downgrade: true
      when: "not gitlab_runner_is_initial_dryrun"  # skip if run for the first time in check mode

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install gitlab-runner from a .deb file
  ansible.builtin.apt:
    deb: "{{ gitlab_runner_deb_file }}"
    allow_downgrade: yes
  when:
    - gitlab_runner_deb_file | length > 0
    - "'gitlab-runner' not in ansible_facts.packages or
      ansible_facts.packages['gitlab-runner'][0].version is version(gitlab_runner_pkg_version, 'ne')"
...
