# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Transpile the flatcar linux configuration"
  ansible.builtin.command: "butane -o /etc/gitlab-runner/ignition.json /etc/gitlab-runner/flatcar-linux-config.bu"
  changed_when: True

- name: Restart GitLab-Runner
  ansible.builtin.service:
    name: gitlab-runner
    state: restarted

...
