# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Prepare
  hosts: all
  tasks:
    - when: ansible_os_family == 'Debian'
      block:
        - name: Install missing dependencies
          ansible.builtin.apt:
            name:
              - sudo              # for `become` privilege escalation
              - iproute2          # for gathering network facts
              - ca-certificates   # for Gitlab-Runner download
            state: present
            update_cache: yes

    - when: ansible_distribution == 'Debian'
      block:
        - name: "Install missing dependencies"
          ansible.builtin.apt:
            name:
              - "iptables"
            state: "present"
            update_cache: yes
        - name: "Use legacy iptables"
          community.general.alternatives:
            name: "iptables"
            path: "/usr/sbin/iptables-legacy"
        - name: "Use legacy ip6tables"
          community.general.alternatives:
            name: "ip6tables"
            path: "/usr/sbin/ip6tables-legacy"

    - when: "gitlab_runner_install_docker"
      name: "Apply geerlingguy.docker role"
      ansible.builtin.include_role:
        name: "geerlingguy.docker"

