# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  schedule:
    - cron: "0 0 * * *"
env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Lint code.
        run: poetry run molecule lint

  license_compliance:
    name: Check license compliance with reuse.
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Lint code.
        run: poetry run reuse lint

  iac-scanning:
    name: Perform Infrastructure as Code Scanning via KICS
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Create the  results directory
        run: mkdir -p results-dir

      - name: Perform KICS scan
        uses: Checkmarx/kics-github-action@v1.6
        with:
          path: 'tasks,templates,vars,defaults,files,handlers'
          output_path: results-dir
          platform_type: ansible
          output_formats: 'sarif'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results-dir/results.sarif

  test:
    name: Run Molecule tests.
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        image:
          - "ghcr.io/hifis-net/ubuntu-systemd:18.04"
          - "ghcr.io/hifis-net/ubuntu-systemd:20.04"
          - "ghcr.io/hifis-net/ubuntu-systemd:22.04"
          - "ghcr.io/hifis-net/debian-systemd:10"
          - "ghcr.io/hifis-net/debian-systemd:11"

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Enable lingering required for podman and systemd in GH Actions.
        run: |  # Compare with https://github.com/eriksjolund/user-systemd-service-actions-workflow/blob/efe872924fd2dd35bb482544126ce751303e14c2/README.md
          sudo loginctl enable-linger $UID
          sleep 1

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Run Molecule tests.
        run: XDG_RUNTIME_DIR=/run/user/$UID poetry run molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.image }}
          REGISTRATION_TOKEN: ${{ secrets.registration_token }}

  release:
    name: Release new version on Ansible Galaxy
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [lint, license_compliance, test]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: "main"
